// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrZ1JlKCzPcUZzFP3_owjm8iIERhGlv38',
    appId: '1:489573537640:web:33bee53af25914b3aa68dd',
    messagingSenderId: '489573537640',
    projectId: 'squadfit-2026',
    authDomain: 'squadfit-2026.firebaseapp.com',
    storageBucket: 'squadfit-2026.firebasestorage.app',
    measurementId: 'G-8J0QZ0CB1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL3uRXI11BFOHhPxN840i_3rDs52oV0RA',
    appId: '1:489573537640:android:e374e919539e0139aa68dd',
    messagingSenderId: '489573537640',
    projectId: 'squadfit-2026',
    storageBucket: 'squadfit-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6_6-NEUOOWAsMusuagQzCM3aA_NrYDvw',
    appId: '1:489573537640:ios:fbf314cb6ce2b7aeaa68dd',
    messagingSenderId: '489573537640',
    projectId: 'squadfit-2026',
    storageBucket: 'squadfit-2026.firebasestorage.app',
    iosBundleId: 'com.example.squadFit',
  );
}
